---
- hosts: host01
  become: true
  vars_files:
     - hem.txt

  tasks:
  - name: Creating user ID 
    user: 
       name : dbadmin
       state: present
       shell: /bin/bash
       createhome: yes
       home: /home/dbadmin
