---
- hosts: fssdev
  become: true
  vars_files:
     - hem.txt

  tasks:
  - name: Creating user ID 
    user: 
       name : enterprisedb
       state: present
       shell: /bin/bash
       createhome: yes
       home: /home/enterprisedb
